# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /programs/clion-2019.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /programs/clion-2019.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sadeep/Desktop/srccc/a/code/gsoc/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sadeep/Desktop/srccc/a/code/gsoc/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/programs/clion-2019.1/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/programs/clion-2019.1/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/programs/clion-2019.1/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/programs/clion-2019.1/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/programs/clion-2019.1/bin/cmake/linux/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/programs/clion-2019.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/programs/clion-2019.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/programs/clion-2019.1/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/programs/clion-2019.1/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(CMAKE_COMMAND) -E cmake_progress_start /home/sadeep/Desktop/srccc/a/code/gsoc/trunk/CMakeFiles /home/sadeep/Desktop/srccc/a/code/gsoc/trunk/src/QtNewGUI/CMakeFiles/progress.marks
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f CMakeFiles/Makefile2 src/QtNewGUI/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sadeep/Desktop/srccc/a/code/gsoc/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f CMakeFiles/Makefile2 src/QtNewGUI/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f CMakeFiles/Makefile2 src/QtNewGUI/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f CMakeFiles/Makefile2 src/QtNewGUI/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/QtNewGUI/CMakeFiles/QtNewGUI.dir/rule:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f CMakeFiles/Makefile2 src/QtNewGUI/CMakeFiles/QtNewGUI.dir/rule
.PHONY : src/QtNewGUI/CMakeFiles/QtNewGUI.dir/rule

# Convenience name for target.
QtNewGUI: src/QtNewGUI/CMakeFiles/QtNewGUI.dir/rule

.PHONY : QtNewGUI

# fast build rule for target.
QtNewGUI/fast:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build
.PHONY : QtNewGUI/fast

# Convenience name for target.
src/QtNewGUI/CMakeFiles/QtNewGUI_autogen.dir/rule:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f CMakeFiles/Makefile2 src/QtNewGUI/CMakeFiles/QtNewGUI_autogen.dir/rule
.PHONY : src/QtNewGUI/CMakeFiles/QtNewGUI_autogen.dir/rule

# Convenience name for target.
QtNewGUI_autogen: src/QtNewGUI/CMakeFiles/QtNewGUI_autogen.dir/rule

.PHONY : QtNewGUI_autogen

# fast build rule for target.
QtNewGUI_autogen/fast:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI_autogen.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI_autogen.dir/build
.PHONY : QtNewGUI_autogen/fast

QtNewGUI_autogen/EWIEGA46WW/qrc_resources.o: QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.o

.PHONY : QtNewGUI_autogen/EWIEGA46WW/qrc_resources.o

# target to build an object file
QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.o:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI.dir/QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.o

QtNewGUI_autogen/EWIEGA46WW/qrc_resources.i: QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.i

.PHONY : QtNewGUI_autogen/EWIEGA46WW/qrc_resources.i

# target to preprocess a source file
QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.i:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI.dir/QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.i

QtNewGUI_autogen/EWIEGA46WW/qrc_resources.s: QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.s

.PHONY : QtNewGUI_autogen/EWIEGA46WW/qrc_resources.s

# target to generate assembly for a file
QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.s:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI.dir/QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : QtNewGUI_autogen/EWIEGA46WW/qrc_resources.cpp.s

QtNewGUI_autogen/mocs_compilation.o: QtNewGUI_autogen/mocs_compilation.cpp.o

.PHONY : QtNewGUI_autogen/mocs_compilation.o

# target to build an object file
QtNewGUI_autogen/mocs_compilation.cpp.o:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI.dir/QtNewGUI_autogen/mocs_compilation.cpp.o
.PHONY : QtNewGUI_autogen/mocs_compilation.cpp.o

QtNewGUI_autogen/mocs_compilation.i: QtNewGUI_autogen/mocs_compilation.cpp.i

.PHONY : QtNewGUI_autogen/mocs_compilation.i

# target to preprocess a source file
QtNewGUI_autogen/mocs_compilation.cpp.i:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI.dir/QtNewGUI_autogen/mocs_compilation.cpp.i
.PHONY : QtNewGUI_autogen/mocs_compilation.cpp.i

QtNewGUI_autogen/mocs_compilation.s: QtNewGUI_autogen/mocs_compilation.cpp.s

.PHONY : QtNewGUI_autogen/mocs_compilation.s

# target to generate assembly for a file
QtNewGUI_autogen/mocs_compilation.cpp.s:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI.dir/QtNewGUI_autogen/mocs_compilation.cpp.s
.PHONY : QtNewGUI_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(MAKE) -f src/QtNewGUI/CMakeFiles/QtNewGUI.dir/build.make src/QtNewGUI/CMakeFiles/QtNewGUI.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... test"
	@echo "... list_install_components"
	@echo "... QtNewGUI"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... QtNewGUI_autogen"
	@echo "... QtNewGUI_autogen/EWIEGA46WW/qrc_resources.o"
	@echo "... QtNewGUI_autogen/EWIEGA46WW/qrc_resources.i"
	@echo "... QtNewGUI_autogen/EWIEGA46WW/qrc_resources.s"
	@echo "... QtNewGUI_autogen/mocs_compilation.o"
	@echo "... QtNewGUI_autogen/mocs_compilation.i"
	@echo "... QtNewGUI_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/sadeep/Desktop/srccc/a/code/gsoc/trunk && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

